version: '2.1'

services:

  # postgres database
  db: 
    image: mdillon/postgis:9.6-alpine
    volumes:
      - pgdata:/var/lib/postgresql/data
      - ./_provisioning/db/init:/docker-entrypoint-initdb.d
      - ./_dumps:/dumps
    environment:
      POSTGRES_PASSWORD: $DB_PASSWORD
      POSTGRES_USER: $DB_USER
    working_dir: /usr/src/app

  api:
    build:
      context: ./_provisioning/api
    depends_on:
      - db

  ui:
    build: 
      context: ./_provisioning/ui
    depends_on:
      - db
      - api
    ports:
      - 3000:3000

  daemon:
    build: 
      context: ./_provisioning/daemon
    depends_on:
      - db
  
volumes:
  pgdata: