version: '2.1'

services:

  db: 
    image: mdillon/postgis:9.6-alpine
    build:
      context: ./_provisioning/db
    volumes:
      - pgdata:/var/lib/postgresql/data
      - ./_provisioning/db/init:/docker-entrypoint-initdb.d
      - ./_dumps:/_dumps
    environment:
      POSTGRES_PASSWORD: $DB_PASSWORD
      POSTGRES_USER: $DB_USER
    working_dir: /usr/src/app 
    ports:
      - 5432:5432

  assemblee: 
    build:
      context: ./_provisioning/an-api
    environment: 
      - ROCKET_ENV=staging
    command: cargo run -p tricoteuses_api_assemblee -- -c Config.toml -v  
    volumes:  
      - ./_data/assemblee-data/:/assemblee-data/
    depends_on:
      - db
    ports: 
      - 8000:8000

  hatvp: 
    build:
      context: ./_provisioning/hatvp-api
    environment: 
      - ROCKET_ENV=staging
    command: cargo run -p tricoteuses_api_hatvp -- -c Config.toml -v 
    volumes:  
      - ./_data/hatvp-data/:/hatvp-data/
    ports: 
      - 8002:8002

  wikidata: 
    build:
      context: ./_provisioning/wikidata-api
    environment: 
      - ROCKET_ENV=staging
    command: cargo run -p tricoteuses_api_wikidata -- -c Config.toml -v
    volumes:  
      - ./_data/wikidata-data:/wikidata-data/
    ports: 
      - 8003:8003

  senat: 
    build:
      context: ./_provisioning/senat-api
    environment: 
      - ROCKET_ENV=staging
    command: cargo run -p tricoteuses_api_senat -- -c Config.toml -v
    volumes:  
      - ./_data/senat-data/:/senat-data/
    ports: 
      - 8004:8004

volumes:
  pgdata:
  _dumps:
  _data: