FROM rustlang/rust:nightly

LABEL AUTHOR="Nelson Herbin <nelson@herbin.info>"
LABEL NAME=tricoteuses-an-api
LABEL VERSION=1

RUN git clone https://framagit.org/tricoteuses/tricoteuses-api-assemblee.git

WORKDIR tricoteuses-api-assemblee
